### ISSUE TITLE
ad object in Banner onAdLoaded callback size is always null

### ISSUE THREAD

**Issue by cisclub** [NZME/react-native-ad-manager#12]
`{ type: 'banner', target: 3222, gadSize: null }`

And that's because in delegate method `adViewDidReceiveAd:` `adView.adSize` is always empty.
I suggest using `adView.frame.size` instead

PR created. https://github.com/NZME/react-native-ad-manager/pull/13

**Comment by simonso-nzme** [comment]
Thanks for that, merged and it's on 1.2.2.
