### ISSUE TITLE
We did not access Example folder of your repo

### ISSUE THREAD

**Issue by RNvivekvision** [NZME/react-native-ad-manager#129]
Why can not access you example folder in your react-native-ad-manager repo?

please give access. so we can use this accordingly.

**Comment by jazdance** [comment]
hmmm, weird, I just tried incognito mode of Chrome,  Edge and FireFox web browsers to access the example link [https://github.com/NZME/react-native-ad-manager/tree/master/example] , I can see those code samples without issues at all, 

also have you tried "git clone" the whole repo to your local machine ? I just tried it too, no issues at all, after the clone, I still can access the example folder without issues too.
