### ISSUE TITLE
update to latest google-mobile-ads-sdk v8

### ISSUE THREAD

**Issue by shifan-wu** [NZME/react-native-ad-manager#14]
It is currently using 7.68.0.  Would it be possible to upgrade this to use 8.0.0?

**Comment by shifan-wu** [comment]
A pull request is created not sure how to link it to this issue. https://github.com/NZME/react-native-ad-manager/pull/15

**Comment by cisclub** [comment]
Does this change build? As per google, there are major changes that requires modifying APIs calls.
https://developers.google.com/admob/ios/migration

**Comment by shifan-wu** [comment]
Yes, this PR is not complete.  One major change needs to happen is DFPBanner changed to GADAdLoader.  I forked this and completed the upgrade on another branch.  But basically updated library to 8.0.0, and remove the DFPBannerView class and use Adloader and GADAdview to complete the implementaiton.

That migration link listed everything.

**Comment by EyMaddis** [comment]
I have a working version here (but disabled facebook integration): https://github.com/simpleTechs/react-native-ad-manager

Feel free to use this as a base to do a proper PR

**Comment by stefanhoth** [comment]
Although this ticket is not updated and the releases are not listed in Github the Google SDKs have been upgraded already
https://github.com/NZME/react-native-ad-manager/commit/5436fa4984646ca0b8cf94598837c08f0e9db1ec

**Comment by matejdr** [comment]
Fixed in this PR: https://github.com/NZME/react-native-ad-manager/pull/35
