### ISSUE TITLE
Current dependency on Google-Mobile-Ads-SDK 7.68.0 break pod installation

### ISSUE THREAD

**Issue by Ebizontek** [NZME/react-native-ad-manager#30]
The react-native-ad-manager depends on Google-Mobile-Ads-SDK 7.68.0 which depends on GoogleAppMeasurement (~> 7.0) as a dependency that fails during pod install. Also I tried both pod update and pod repo update. Here, I provided some screenshots for reference. Thanks!

<img width="1047" alt="Screenshot 2021-07-21 at 4 06 32 PM" src="https://user-images.githubusercontent.com/87758581/126475783-560bf2ff-e21b-4516-91dd-412469dda1dd.png">

<img width="519" alt="Screenshot 2021-07-21 at 4 12 37 PM" src="https://user-images.githubusercontent.com/87758581/126476298-fd08a305-04da-4b41-aa60-749f14730381.png">

**Comment by EyMaddis** [comment]
I am currently upgrading the SDK on this branch: https://github.com/simpleTechs/react-native-ad-manager, however it does not provide Facebook integration but I made it work with firebase :)

**Comment by matejdr** [comment]
Fixed in this PR: https://github.com/NZME/react-native-ad-manager/pull/35
