### ISSUE TITLE
Custom ad sizes

### ISSUE THREAD

**Issue by peterwiebe** [NZME/react-native-ad-manager#41]
The SDK for GAM shows the ability to create custom sized ads, is there any intention to support that or no?
https://developers.google.com/ad-manager/mobile-ads-sdk/ios/banner#custom_ad_sizes

**Comment by adniltonsantos** [comment]
Hi @peterwiebe , how are you ? I recently added a PR . But, it uses my fork and test, working via ios and Android . 
in the adSize component, use adSize="320x50" or adSize={740x300} ...

**Comment by matejdr** [comment]
fixed: https://github.com/NZME/react-native-ad-manager/pull/53/files#diff-88d23f79f39ba76dadc2fcea2e8fa71d6e333f12b3e28a00897e9ea462484907
