### ISSUE TITLE
`smartBannerPortrait` ad size is not suppored on iOS

### ISSUE THREAD

**Issue by przemyslawzalewski** [NZME/react-native-ad-manager#46]
I noticed on iOS that sometimes we receive the following errror:

```
[native] Error setting property 'validAdSizes' of CTKBannerView with tag #15447: Invalid adSize smartBannerPortrait
```

We set valid ad sizes to list similar to `['banner', 'largeBanner', 'mediumRectangle', 'smartBannerPortrait']`.

The supported ad sizes lists this as a valid one at: https://github.com/NZME/react-native-ad-manager/blob/91ff75283d253c5de8334f42dcee987622e6950e/src/CTKAdManagerBanner.js#L100-L113

However, on iOS the code seems to be commented out:

https://github.com/NZME/react-native-ad-manager/commit/f4a74fe5e4a3d2dc5df1bb339dee0734f4f4e61c#diff-a5e6266736fa911df1e20cba92359aa0513c35fbb88b172e167024eb518edef9R22-R25

Was that intended change?

**Comment by matejdr** [comment]
https://developers.google.com/admob/ios/banner#banner_sizes
smartBannerPortrait and smartBannerLandscape are not supported any more

Only supported sizes are: GADAdSizeBanner, GADAdSizeLargeBanner, GADAdSizeMediumRectangle, GADAdSizeFullBanner, GADAdSizeLeaderboard

Although custom sizes are supported here: https://github.com/NZME/react-native-ad-manager/blob/58ca9f42b7ff27382e5e67138f75b9507a721322/android/src/main/java/com/matejdr/admanager/utils/AdSizeUtil.java#L6
Meaning any two sizes split by _x_.  Does not mean all sizes will work if there is no inventory.
