### ISSUE TITLE
Android building failed

### ISSUE THREAD

**Issue by ghost** [NZME/react-native-ad-manager#50]
Hello,

could you please change on [build.gradle](https://github.com/NZME/react-native-ad-manager/blob/master/android/build.gradle)

Line 77 =>    `implementation 'com.google.ads.mediation:facebook:5.10.0.0'` to 6.8.0.0

The version 5.10.0.0 is no longer available
[Official android dependencies doc ](https://maven.google.com/web/index.html?q=com.google.ads.mediation#com.google.ads.mediation:facebook)

**Comment by syed-imam** [comment]
Hi, any word on this? It's still broken on version ` 1.3.6`. @GuillemetS did you find a solution to this? I greatly appreciate it if you can share your solution

**Comment by GuillemetS** [comment]
Hi, 
I use "patch-package" to force the version

```
diff --git a/node_modules/react-native-ad-manager/android/build.gradle b/node_modules/react-native-ad-manager/android/build.gradle
--- a/node_modules/react-native-ad-manager/android/build.gradle
+++ b/node_modules/react-native-ad-manager/android/build.gradle
@@ -74,7 +74,7 @@
     //noinspection GradleDynamicVersion
     implementation 'com.facebook.react:react-native:+'  // From node_modules
     implementation 'com.google.android.gms:play-services-ads:20.3.0'
-    implementation 'com.google.ads.mediation:facebook:5.10.0.0'
+    implementation 'com.google.ads.mediation:facebook:6.8.0.0'
 }
 
 def configureReactNativePom(def pom) {
```

**Comment by syed-imam** [comment]
@GuillemetS thanks for responding so quickly. I actually ended up using this package https://github.com/sbugert/react-native-admob/

**Comment by rafauke** [comment]
FYI @GuillemetS  I have create a PR #54 that should address the failing build issue.

**Comment by Freddixx** [comment]
Hi, since this project is largely abandoned, we have decided to fork and maintain it on our own. We have already released a couple of fixes. If you would like to contribute there, please go ahead. Any help is welcome ☺️ 

https://github.com/Freddixx/react-native-ad-manager
https://www.npmjs.com/package/@freddixx/react-native-ad-manager

**Comment by aleccolville-nzme** [comment]
closing issue as implemented now
