### ISSUE TITLE
Ads are not displayed on Android 12

### ISSUE THREAD

**Issue by dbilgin** [NZME/react-native-ad-manager#52]
I have tried this on iOS devices and any other Android devices and it works fine, but for Android 12 I am having problems.
I have a Pixel 5 device and when I try to display ads on this device I get the error `The ad request was successful, but no ad was returned due to lack of ad inventory.`. This happens for all types of ads (banners, native etc.). The same thing doesn't happen with any other type of device.
I have also tried checking these out on a release build and it's still the same thing. I have also added the work-runtime as below as mentioned [here](https://developers.google.com/ad-manager/mobile-ads-sdk/android/quick-start):
```

    constraints {
        implementation('androidx.work:work-runtime:2.7.0') {
            because '''androidx.work:work-runtime:2.1.0 pulled from play-services-ads
                   has a bug using PendingIntent without FLAG_IMMUTABLE or
                   FLAG_MUTABLE and will fail in apps targeting S+.'''
        }
    }
```

This just avoids crashing the app but has no effect on displaying the actual ads.

Also, I definitely have live ads and this doesn't only happen with those, I am also using the example ads shown [here](https://developers.google.com/ad-manager/mobile-ads-sdk/android/test-ads). I am assuming at least these should be working.

**Comment by Freddixx** [comment]
Hi, since this project is largely abandoned, we have decided to fork and maintain it on our own. We have already released a couple of fixes. If you would like to contribute there, please go ahead. Any help is welcome ☺️ 

https://github.com/Freddixx/react-native-ad-manager
https://www.npmjs.com/package/@freddixx/react-native-ad-manager

**Comment by dbilgin** [comment]
Thanks for the suggestion @Freddixx, no one seems to be checking the issues here anyway as you said.
