### ISSUE TITLE
bitcode error 

### ISSUE THREAD

**Issue by kanchanchd1989** [NZME/react-native-ad-manager#8]
After installing the package as mentioned in the ReadMe file, when i try to start the app, the build is failed with the following error and it seems that react native ad manager needs FBAudienceNetwork lib which is causing this issue : 
<Error>
reactnative/NASCAR/ios/Pods/FBAudienceNetwork/Static/FBAudienceNetwork.framework/FBAudienceNetwork(FBANInterstitialAdAdapter.m.o), could not parse object file /Users/ksharma/Desktop/nascar-reactnative/NASCAR/ios/Pods/FBAudienceNetwork/Static/FBAudienceNetwork.framework/FBAudienceNetwork(FBANInterstitialAdAdapter.m.o): ’Invalid bitcode version (Producer: ‘1103.0.32.59.0_0’ Reader: ‘1100.0.33.8_0’)’, using libLTO version ‘LLVM version 11.0.0, (clang-1100.0.33.8)’ file ‘/Users/ksharma/Desktop/nascar-reactnative/NASCAR/ios/Pods/FBAudienceNetwork/Static/FBAudienceNetwork.framework/FBAudienceNetwork’ for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

</Error>

We don't want to disable bitcode as Apple uses it to optimize the app. Please suggest how to fix this issue. Thanks !!

**Comment by aleccolville-nzme** [comment]
bitcode obsolete now, closing issue
