### ISSUE TITLE
Is a new release planned with the recent change to the podspec file?

### ISSUE THREAD

**Issue by zubko** [NZME/react-native-ad-manager#99]
Hi, I want to use the recent update of the version of Google-Mobile-Ads-SDK: https://github.com/NZME/react-native-ad-manager/blob/51087f2fe3797feacf4cd33abdfe8cf43702a886/react-native-ad-manager.podspec#L23

I can use the commit from GitHub directly, but it would be nice if there was a new patch version to use it more cleanly. Or am I missing smth?

**Comment by zubko** [comment]
https://github.com/NZME/react-native-ad-manager/pull/100

I've made a PR if it helps

**Comment by aleccolville-nzme** [comment]
yes, very shortly : )
